### ISSUE TITLE
git clone 回來後就有問題嚕

### ISSUE THREAD

**Issue by alanchang15** [bangformis/bang.mvc#1]
Fatal error: Call to undefined function session_status() in D:\Server\www\php53\bang-mvc\Bang\Lib\Session.php on line 17

所以不支援 php 5.3 對吧!!

**Comment by alanchang15** [comment]
改這樣後又有其他問題
    public static function StartSession() {
        if (version_compare(PHP_VERSION, '5.3')) {
            if (!session_id()) {
                session_start();
            }
        }
        else {
            if (session_status() == PHP_SESSION_NONE) {
                session_start();
            }
        }
    }

Fatal error: Uncaught exception 'Exception' with message '找不到 Memcache 這個Class檔案，無法載入！' in D:\Server\www\php53\bang-mvc\System.php:90 Stack trace: #0 D:\Server\www\php53\bang-mvc\Bang\Lib\Appstore.php(67): __autoload('Memcache') #1 D:\Server\www\php53\bang-mvc\Bang\Lib\Appstore.php(21): Appstore::Current() #2 D:\Server\www\php53\bang-mvc\Controllers\HomeController.php(26): Appstore::Set('name', 'value') #3 [internal function]: HomeController->Index() #4 D:\Server\www\php53\bang-mvc\Bang\MVC\Route.php(39): ReflectionMethod->invoke(Object(HomeController)) #5 D:\Server\www\php53\bang-mvc\index.php(6): Route->invoke() #6 {main} thrown in D:\Server\www\php53\bang-mvc\System.php on line 90

**Comment by alanchang15** [comment]
所以是我沒裝 php_memcache~~哈哈
可以加設定預設不使用 memcache
不然很多新手不知所措....

**Comment by bangformis** [comment]
感謝建議，已經改為memcache可以開關決定是否使用，在Config中可以設定，若為關閉時，將會自動改為以註冊表直接代替memcache
